<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_ShippingDetailsTitle</name>
   <tag></tag>
   <elementGuidId>c15ca867-3be4-4193-9c4c-1b0c2c1d3bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
//h3[.='Shipping details']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>060b37c1-936b-4d29-a48d-73aa8eeb6371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-800 px-5 md:px-0 text-2xl lg:text-3xl font-bold uppercase mb-7</value>
      <webElementGuid>b5de5b05-7d20-45d7-978a-ea33983b3003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>
//h3[.='Shipping details']</value>
      <webElementGuid>a5156bf4-fdea-4fbe-a18a-844dabb240a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipping details</value>
      <webElementGuid>9c0614be-d978-4e89-ae95-96a251c381a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f9103fa7-a0c3-4257-9f96-63618723e997</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
