<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Registration</name>
   <tag></tag>
   <elementGuidId>ca647a18-a576-44cf-a558-c95b4535cfee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1[(text() = 'Registration' or . = 'Registration')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='list-inline-item ng-binding']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.text-3xl</value>
      <webElementGuid>b45dfe3e-c5a8-4a09-b02d-a2591ddf8674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>05a52000-4148-461c-ae78-d26dfcff5c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registration</value>
      <webElementGuid>2f4dbd3d-b867-4e1e-b958-b8ec2cd53145</webElementGuid>
   </webElementProperties>
</WebElementEntity>
