<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Organization</name>
   <tag></tag>
   <elementGuidId>f183e2ad-0ef0-42b4-9bdc-43e12210d495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for = 'personalRadio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ddfe9b8d-d07f-4a50-8085-3e606c73353a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal Use</value>
      <webElementGuid>5240711e-82ba-483d-acbe-d31b5b1a53ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>personalRadio</value>
      <webElementGuid>31de5bff-a4cc-4210-9671-c4af50062c1e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
