<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EmailButton</name>
   <tag></tag>
   <elementGuidId>67646b86-777f-48d6-88cc-cde3d4ec25d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Email')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fa4c795-62dd-4338-8714-68d7059def28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link font-weight-bold</value>
      <webElementGuid>67422ba7-d9ef-4890-874f-b7d8e5a9e8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>sendToEmail()</value>
      <webElementGuid>beb9540d-4830-42da-ad63-be283c1e7f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Email</value>
      <webElementGuid>10392ea6-482d-4126-a514-76daaa22461d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-cart ng-scope&quot;]/main[@class=&quot;container flex-grow-1 pt-4 pb-6 ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;d-none d-md-block col-md-12 mb-4&quot;]/div[@class=&quot;page-header clearfix d-flex align-items-center&quot;]/ul[@class=&quot;list-inline mb-0 ml-auto&quot;]/li[@class=&quot;list-inline-item&quot;]/a[@class=&quot;btn btn-link font-weight-bold&quot;]</value>
      <webElementGuid>407998cc-8ecc-46f6-8f84-9e976b5128ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Email')]</value>
      <webElementGuid>31c7cbd5-db0c-4102-8d3d-c8f0571c7c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete'])[1]/following::a[2]</value>
      <webElementGuid>61563467-982b-4105-bed0-d27f79f41cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CO211126-00001'])[1]/preceding::a[2]</value>
      <webElementGuid>a9fc7844-6729-4af8-9733-f77a1c4e8e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[24]</value>
      <webElementGuid>4e7c05c1-77b5-4d72-9a5d-5b07247f2f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul[2]/li[2]/a</value>
      <webElementGuid>0eff8d50-c034-4a5a-a292-b7f72a75e91e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
