<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpanSubtotal</name>
   <tag></tag>
   <elementGuidId>ff763c4d-6002-4aae-9ef2-b16e93801470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@ng-bind = '$ctrl.order[$ctrl.fieldNames.subTotal].formattedAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>$ctrl.order[$ctrl.fieldNames.subTotal].formattedAmount</value>
   </webElementProperties>
</WebElementEntity>
