<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Logo</name>
   <tag></tag>
   <elementGuidId>93094b86-debe-4460-9a56-25192ccebd77</elementGuidId>
   <imagePath>C:\Users\Eka\Desktop\Virtoway_projects\Katalon\Screenshots\Targets\Page_Virto Commerce Demo B2B Online Shopping for you - B2B-store\img.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;B2B-store&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//img[@alt = 'B2B-store' and @src = '/B2B-store/themes/assets/b2b-promo-logo.png']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='B2B-store']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\Eka\Desktop\Virtoway_projects\Katalon\Screenshots\Targets\Page_Virto Commerce Demo B2B Online Shopping for you - B2B-store\img.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>B2B-store</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/B2B-store/themes/assets/b2b-promo-logo.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>logo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-index ng-scope&quot;]/header[@class=&quot;d-none d-md-block&quot;]/nav[@class=&quot;navbar-dark bg-dark py-2&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-6 d-flex align-items-center&quot;]/a[@class=&quot;navbar-brand&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='B2B-store']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
