<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RemovePurchasedCode</name>
   <tag></tag>
   <elementGuidId>5902ef88-c99d-4b7b-affe-fc15bfef9a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value> [ng-if='purchaseOrderNumberExist() &amp;&amp; !purchaseOrderNumberChanged()']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='removePurchaseOrderNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
</WebElementEntity>
