<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseMessage</name>
   <tag></tag>
   <elementGuidId>5161a6b4-ff70-4749-83bd-fdc162cfaf88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[.='×']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label='Close']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
