<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_EmailCheckBox</name>
   <tag></tag>
   <elementGuidId>d6c2ce4d-8b05-4b62-8a25-c3fd4bd62510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>&lt;input type=&quot;checkbox&quot; id=&quot;8d05a60f-6e93-4a08-8208-4755a68e04f3&quot; class=&quot;custom-control-input ng-pristine ng-untouched ng-valid ng-empty&quot; ng-model=&quot;organizationMemberChecks[member.id]&quot; xpath=&quot;1&quot;></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[ng-model='organizationMemberChecks[member.id]']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-cart ng-scope modal-open&quot;]/div[@class=&quot;modal fade ng-scope ng-isolate-scope show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body pt-0 ng-scope&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[1]/div[@class=&quot;custom-control custom-checkbox&quot;]/label[@class=&quot;custom-control-label&quot;][count(. | //input[@for = '8d05a60f-6e93-4a08-8208-4755a68e04f3' and @class = 'custom-control-input ng-valid ng-not-empty ng-dirty ng-valid-parse ng-touched' and @type = 'checkbox' and @id = '8d05a60f-6e93-4a08-8208-4755a68e04f3']) = count(//input[@for = '8d05a60f-6e93-4a08-8208-4755a68e04f3' and @class = 'custom-control-input ng-valid ng-not-empty ng-dirty ng-valid-parse ng-touched' and @type = 'checkbox' and @id = '8d05a60f-6e93-4a08-8208-4755a68e04f3'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>8d05a60f-6e93-4a08-8208-4755a68e04f3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-input ng-valid ng-not-empty ng-dirty ng-valid-parse ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-cart ng-scope modal-open&quot;]/div[@class=&quot;modal fade ng-scope ng-isolate-scope show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body pt-0 ng-scope&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[1]/div[@class=&quot;custom-control custom-checkbox&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8d05a60f-6e93-4a08-8208-4755a68e04f3</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/label</value>
   </webElementXpaths>
</WebElementEntity>
