<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UpdateProductCount</name>
   <tag></tag>
   <elementGuidId>65fffcf1-bfa6-4b1d-b1bf-f4d977c07ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//
input[@type = 'number']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>
input</value>
      <webElementGuid>8a0bfcbf-364e-4dd0-9269-09195d9a2127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c824c4c0-798f-47c7-b8e5-2836e4577cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c6766a0e-0cd1-42c4-8c47-26b819bc1814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
