<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ContinueShopping</name>
   <tag></tag>
   <elementGuidId>bb6f61f9-f29b-409a-97c6-e40000101148</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//
span[@class = 'vc-button__content']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>
span</value>
      <webElementGuid>684f9728-eeaa-4818-9ce6-4d163907f250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.vc-button__content</value>
      <webElementGuid>2e3a3072-7c90-4e4c-a90b-5426b5f24b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>7cca1477-89c0-4d2e-bc3b-00f0e722ba5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1559eaa4-0d9d-49d9-a6fa-f969411a2b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
