<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OrderNotification</name>
   <tag></tag>
   <elementGuidId>5b90d593-3ad8-4822-9733-6a69b95d73f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
.px-5.text-green-700</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.card-header.text-uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>19d47fcb-7d3e-4f10-85d7-2d4a618afb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.px-5.text-green-700</value>
      <webElementGuid>ceae6bf1-a780-474e-a9d2-509a8ad32568</webElementGuid>
   </webElementProperties>
</WebElementEntity>
