<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gift</name>
   <tag></tag>
   <elementGuidId>a0b83f11-6e79-4005-a1c2-3d7c46fe9541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.pl-md-2 > .card</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>.items-center.flex-grow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b7eaa19-e036-4584-bbdf-5450a4261681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.items-center.flex-grow</value>
      <webElementGuid>76ae764a-d57d-4a88-9210-8bac1c3eb92f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
