<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ImageSearchResultItem</name>
   <tag></tag>
   <elementGuidId>0c03da04-f370-4e27-b902-99d5356100be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='electronics']/main/div/div/div/div/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>//qademovc.blob.core.windows.net/catalog/16993868/Beats-by-Dre-Powerbeats-2-In-ear-Bluetooth-Wireless-Sport-Headphones-f216d237-779c-48c5-82a8-51a0de248169_168x168.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fallback-src</name>
      <type>Main</type>
      <value>//qademovc.blob.core.windows.net/catalog/16993868/Beats-by-Dre-Powerbeats-2-In-ear-Bluetooth-Wireless-Sport-Headphones-f216d237-779c-48c5-82a8-51a0de248169.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//qademovc.blob.core.windows.net/catalog/16993868/Beats-by-Dre-Powerbeats-2-In-ear-Bluetooth-Wireless-Sport-Headphones-f216d237-779c-48c5-82a8-51a0de248169_168x168.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;electronics&quot;)/main[@class=&quot;wrapper main-content&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;grid-item&quot;]/div[@class=&quot;grid-uniform&quot;]/div[@class=&quot;grid-item search-result large--one-fifth medium--one-third small--one-half&quot;]/a[@class=&quot;product-grid-item&quot;]/div[@class=&quot;product-grid-image&quot;]/div[@class=&quot;product-grid-image--centered&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='electronics']/main/div/div/div/div/a/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
