<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>_DARFT_PromoCreate</name>
   <tag></tag>
   <elementGuidId>20bdaba1-d794-494f-80f9-9a7978a86cea</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  //\&quot;id\&quot;: \&quot;${id}\&quot;,\n  \&quot;name\&quot;: \&quot;${name}\&quot;,\n  \&quot;type\&quot;: \&quot;${type}\&quot;,\n  \&quot;referenceCode\&quot;: \&quot;${referenceCode}\&quot;,\n  \&quot;startDate\&quot;: \&quot;${startDate}\&quot;,\n  \&quot;endDate\&quot;: \&quot;${endDate}\&quot;,\n  \&quot;region\&quot;: \&quot;${region}\&quot;,\n  \&quot;priority\&quot;: \&quot;${priority}\&quot;,\n  \&quot;isExclusive\&quot;: \&quot;${isExclusive}\&quot;,\n  \&quot;maxActivationCount\&quot;: \&quot;${maxActivationCount}\&quot;,\n  \&quot;linkedId\&quot;: \&quot;${linkedId}\&quot;,\n  \&quot;isActive\&quot;: \&quot;${isActive}\&quot;,\n  \&quot;items\&quot;: [\n    {\n      \&quot;customerConditions\&quot;: [\n        {\n          \&quot;outletId\&quot;: \&quot;${itemsCustomerConditions}\&quot;,\n          \&quot;userGroups\&quot;: [\n            \&quot;${itemsCustomerConditionsUserGroups1}\&quot;\n          ],\n          \&quot;startDate\&quot;: \&quot;${itemsCustomerConditionsStartDate}\&quot;,\n          \&quot;endDate\&quot;: \&quot;${itemsCustomerConditionsEndDate}\&quot;\n        }\n      ],\n      \&quot;productConditions\&quot;: [\n        {\n          \&quot;sku\&quot;: \&quot;${itemsProductConditionsSku}\&quot;,\n          \&quot;minQuantity\&quot;: \&quot;${itemsProductConditionsMinQuantity}\&quot;,\n          \&quot;maxQuantity\&quot;: \&quot;${itemsProductConditionsMinQuantity}\&quot;,\n          \&quot;startDate\&quot;: \&quot;${itemsProductConditionsStartDate}\&quot;,\n          \&quot;endDate\&quot;: \&quot;${itemsProductConditionsEndDate}\&quot;,\n          \&quot;standardRatio\&quot;: \&quot;${itemsProductConditionsStandardRatio}\&quot;\n        }\n      ],\n      \&quot;effects\&quot;: [\n        {\n          \&quot;discount\&quot;: {\n            \&quot;absoluteAmount\&quot;: \&quot;${itemsEffectsDiscountAbsoluteAmount}\&quot;,\n            \&quot;relativeAmount\&quot;: \&quot;${itemsEffectsDiscountRelativeAmount}\&quot;,\n            \&quot;sku\&quot;: \&quot;${itemsEffectsDiscountSku}\&quot;\n          },\n          \&quot;freeOfCharge\&quot;: {\n            \&quot;sku\&quot;: \&quot;${itemsEffectsFreeOfChargeSku}\&quot;,\n            \&quot;quantity\&quot;: \&quot;${itemsEffectsFreeOfChargeQuantity}\&quot;\n          },\n          \&quot;promoOnPromo\&quot;: {\n            \&quot;sku\&quot;: \&quot;${itemsEffectsPromoOnPromoSku}\&quot;,\n            \&quot;minQuantity\&quot;: \&quot;${itemsEffectsPromoOnPromoMinQuantity}\&quot;,\n            \&quot;maxQuantity\&quot;: \&quot;${itemsEffectsPromoOnPromoMaxQuantity}\&quot;,\n            \&quot;absoluteAmount\&quot;: \&quot;${itemsEffectsPromoOnPromoAbsoluteAmount}\&quot;,\n            \&quot;relativeAmount\&quot;: \&quot;${itemsEffectsPromoOnPromoRelativeAmount}\&quot;,\n            \&quot;freeOfChargeSku\&quot;: \&quot;${itemsEffectsPromoOnPromoFreeOfChargeSku}\&quot;,\n            \&quot;freeOfChargeQuantity\&quot;: \&quot;${itemsEffectsPromoOnPromoFreeOfChargeQuantity}\&quot;\n          }\n        }\n      ]\n    }\n  ]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>api_key</name>
      <type>Main</type>
      <value>${GlobalVariable.api_key}</value>
   </httpHeaderProperties>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${GlobalVariable.urlBack}/api/marketing/promotions</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'AutoTestId'</defaultValue>
      <description></description>
      <id>6ae60c7b-5982-462e-8726-e0d0e5f9eaec</id>
      <masked>false</masked>
      <name>id</name>
   </variables>
   <variables>
      <defaultValue>'QwePromo'</defaultValue>
      <description></description>
      <id>ba6aecb7-06bc-4cc6-ad86-646e27167b1f</id>
      <masked>false</masked>
      <name>name</name>
   </variables>
   <variables>
      <defaultValue>'AutoPromoType'</defaultValue>
      <description></description>
      <id>ad73b4ce-e982-48e0-b419-2cc844c5f19e</id>
      <masked>false</masked>
      <name>type</name>
   </variables>
   <variables>
      <defaultValue>'AutoPromoRef'</defaultValue>
      <description></description>
      <id>899fa618-ac47-425a-8e3d-b297d29ebaf5</id>
      <masked>false</masked>
      <name>referenceCode</name>
   </variables>
   <variables>
      <defaultValue>'2020-01-03T09:31:26.961Z'</defaultValue>
      <description></description>
      <id>d5f822a0-006d-453f-8f65-6768dc0c8d2c</id>
      <masked>false</masked>
      <name>startDate</name>
   </variables>
   <variables>
      <defaultValue>'2045-07-03T09:31:26.961Z'</defaultValue>
      <description></description>
      <id>941978cb-a949-4b74-a94c-85ae59cfe02f</id>
      <masked>false</masked>
      <name>endDate</name>
   </variables>
   <variables>
      <defaultValue>'AutoReg'</defaultValue>
      <description></description>
      <id>ac44ccf7-ab24-44dd-b56c-8b29c8118434</id>
      <masked>false</masked>
      <name>region</name>
   </variables>
   <variables>
      <defaultValue>1</defaultValue>
      <description></description>
      <id>a51d83d4-f80b-43fb-825c-9a4ed12dba8c</id>
      <masked>false</masked>
      <name>priority</name>
   </variables>
   <variables>
      <defaultValue>false</defaultValue>
      <description></description>
      <id>f9690627-8ad2-44b0-ac99-842e4893d4d8</id>
      <masked>false</masked>
      <name>isExclusive</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>9ee633be-46d3-4075-a304-c2c4dc019602</id>
      <masked>false</masked>
      <name>maxActivationCount</name>
   </variables>
   <variables>
      <defaultValue>'AutoLinkID'</defaultValue>
      <description></description>
      <id>bf160866-c1d3-4fcc-b702-655534c26f0c</id>
      <masked>false</masked>
      <name>linkedId</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>2040dfe8-22a9-4f33-8cc6-b2295a50a966</id>
      <masked>false</masked>
      <name>isActive</name>
   </variables>
   <variables>
      <defaultValue>'123472'</defaultValue>
      <description></description>
      <id>445a1b9d-4807-43be-9965-70280338f3bb</id>
      <masked>false</masked>
      <name>itemsCustomerConditionsOutletId</name>
   </variables>
   <variables>
      <defaultValue>'AutoUserGroup1'</defaultValue>
      <description></description>
      <id>259f82a5-7ac3-4a35-b3b2-c9e30d541bdf</id>
      <masked>false</masked>
      <name>itemsCustomerConditionsUserGroups1</name>
   </variables>
   <variables>
      <defaultValue>'2020-04-03T09:31:26.961Z'</defaultValue>
      <description></description>
      <id>e8ad2b2e-c099-46b3-83e5-b9cd0f30e81e</id>
      <masked>false</masked>
      <name>itemsCustomerConditionsStartDate</name>
   </variables>
   <variables>
      <defaultValue>'2045-06-03T09:31:26.961Z'</defaultValue>
      <description></description>
      <id>4631ac2a-bf03-42f3-8682-dcfd17f85087</id>
      <masked>false</masked>
      <name>itemsCustomerConditionsEndDate</name>
   </variables>
   <variables>
      <defaultValue>'53653'</defaultValue>
      <description></description>
      <id>fb748795-3bc8-49ad-b056-6166ac1db623</id>
      <masked>false</masked>
      <name>itemsProductConditionsSku</name>
   </variables>
   <variables>
      <defaultValue>10</defaultValue>
      <description></description>
      <id>43dc62b5-7dce-48c4-a6e3-369b46f68897</id>
      <masked>false</masked>
      <name>itemsProductConditionsMinQuantity</name>
   </variables>
   <variables>
      <defaultValue>20</defaultValue>
      <description></description>
      <id>19710b23-7081-4c31-977a-a535359fe0a3</id>
      <masked>false</masked>
      <name>itemsProductConditionsMaxQuantity</name>
   </variables>
   <variables>
      <defaultValue>'2020-05-03T09:31:26.961Z'</defaultValue>
      <description></description>
      <id>b1213790-0f08-47a9-b501-7a5fe122a201</id>
      <masked>false</masked>
      <name>itemsProductConditionsStartDate</name>
   </variables>
   <variables>
      <defaultValue>'2045-06-03T09:31:26.961Z'</defaultValue>
      <description></description>
      <id>57d51a55-5ec4-44dc-9db4-c49e7d732528</id>
      <masked>false</masked>
      <name>itemsProductConditionsEndDate</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>87b72d55-ce9a-409b-a656-db1560ea31fe</id>
      <masked>false</masked>
      <name>itemsProductConditionsStandardRatio</name>
   </variables>
   <variables>
      <defaultValue>10</defaultValue>
      <description></description>
      <id>e58272f7-009a-4157-97b5-3b04a2b93fef</id>
      <masked>false</masked>
      <name>itemsEffectsDiscountAbsoluteAmount</name>
   </variables>
   <variables>
      <defaultValue>20</defaultValue>
      <description></description>
      <id>a61aafee-aad2-43fc-8b47-a57c317654eb</id>
      <masked>false</masked>
      <name>itemsEffectsDiscountRelativeAmount</name>
   </variables>
   <variables>
      <defaultValue>'1885'</defaultValue>
      <description></description>
      <id>d3b11602-617b-4620-b600-e831943929b3</id>
      <masked>false</masked>
      <name>itemsEffectsDiscountSku</name>
   </variables>
   <variables>
      <defaultValue>'101651'</defaultValue>
      <description></description>
      <id>d2c1999e-faba-4b18-9100-7f0911066a81</id>
      <masked>false</masked>
      <name>itemsEffectsFreeOfChargeSku</name>
   </variables>
   <variables>
      <defaultValue>2</defaultValue>
      <description></description>
      <id>ab195ca8-ae9a-4344-aa54-f64f75815bcb</id>
      <masked>false</masked>
      <name>itemsEffectsFreeOfChargeQuantity</name>
   </variables>
   <variables>
      <defaultValue>'54071'</defaultValue>
      <description></description>
      <id>556a66a0-8b60-47b5-9be9-3462ea2ff108</id>
      <masked>false</masked>
      <name>itemsEffectsPromoOnPromoSku</name>
   </variables>
   <variables>
      <defaultValue>1</defaultValue>
      <description></description>
      <id>b0c49728-64d1-4b82-aa63-fc81e2c1b4de</id>
      <masked>false</masked>
      <name>itemsEffectsPromoOnPromoMinQuantity</name>
   </variables>
   <variables>
      <defaultValue>3</defaultValue>
      <description></description>
      <id>f852ddab-7b36-4ab6-9941-7a7721db745a</id>
      <masked>false</masked>
      <name>itemsEffectsPromoOnPromoMaxQuantity</name>
   </variables>
   <variables>
      <defaultValue>15</defaultValue>
      <description></description>
      <id>29a1d398-dc15-4f69-9358-9af7f5a0bc66</id>
      <masked>false</masked>
      <name>itemsEffectsPromoOnPromoAbsoluteAmount</name>
   </variables>
   <variables>
      <defaultValue>22</defaultValue>
      <description></description>
      <id>bd6aca53-a4d7-4a42-b584-45a9b873af20</id>
      <masked>false</masked>
      <name>itemsEffectsPromoOnPromoRelativeAmount</name>
   </variables>
   <variables>
      <defaultValue>'1884'</defaultValue>
      <description></description>
      <id>c7120d66-95d3-48f4-9d87-ad5c65fbf662</id>
      <masked>false</masked>
      <name>itemsEffectsPromoOnPromoFreeOfChargeSku</name>
   </variables>
   <variables>
      <defaultValue>1</defaultValue>
      <description></description>
      <id>03c67c84-b794-4e00-8d4c-b3c8249b0b4d</id>
      <masked>false</masked>
      <name>itemsEffectsPromoOnPromoFreeOfChargeQuantity</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonOutput
import com.kms.katalon.core.util.KeywordUtil


ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()
def prettyJson = JsonOutput.prettyPrint(response.getResponseBodyContent())
KeywordUtil.logInfo(prettyJson)
WS.verifyResponseStatusCode(response, 200)
</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
