<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_HideComparePupUp</name>
   <tag></tag>
   <elementGuidId>43d88090-cfe8-4c59-89c5-e5b7248a642d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//span[.='Hide']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
