<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_ProductTitle2</name>
   <tag></tag>
   <elementGuidId>0176f1b6-4c0e-4f8d-a9d7-6c2377fcbb5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='epson-expression-premium-xp-820-wireless-color-photo-printercopierscannerfax-machine']/main/div[2]/div/ng-controller/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e26fc488-40c2-4f79-b308-81fe3f391f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Epson Expression Premium XP-820 Wireless Color Photo Printer/Copier/Scanner/Fax Machine</value>
      <webElementGuid>71a05a3f-f98a-4bf0-8dd2-e9c46efcbb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;epson-expression-premium-xp-820-wireless-color-photo-printercopierscannerfax-machine&quot;)/main[@class=&quot;container pt-4 pb-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/ng-controller[@class=&quot;ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/h1[1]</value>
      <webElementGuid>91a1e77a-ad79-426d-9797-423db5566e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='epson-expression-premium-xp-820-wireless-color-photo-printercopierscannerfax-machine']/main/div[2]/div/ng-controller/div/div/h1</value>
      <webElementGuid>fad971ce-51c5-4524-93de-f8451e709a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Epson Expression Premium XP-820 Wireless Color Photo Printer/Copier/Scanner/Fax Machine'])[1]/following::h1[1]</value>
      <webElementGuid>784930ff-b6c3-427a-824b-fdd8565d5bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inkjet Printers'])[1]/following::h1[1]</value>
      <webElementGuid>d2db4ec5-74eb-41b4-99f9-ea7677bfcb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item #'])[1]/preceding::h1[1]</value>
      <webElementGuid>44d911c6-53ce-404f-af99-b7e92e460f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mfr. model #'])[1]/preceding::h1[1]</value>
      <webElementGuid>489fd089-3fdf-475d-ba09-73f668a46ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>22da7e53-fcf5-46b1-bca0-c93c15b4ecda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
