<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PaymentMethod2</name>
   <tag></tag>
   <elementGuidId>d442bf99-fdb6-479e-8487-49864ef5159a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.w-full.flex-grow > div:nth-of-type(3) > div:nth-of-type(2) > div:nth-of-type(2) span:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='lg:w-3/4 xl:w-4/5 flex-grow w-full']/div[4]//span[@class='vc-button__content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d6bc00d-34de-43c4-86a3-f7659dc3601b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.w-full.flex-grow > div:nth-of-type(3) > div:nth-of-type(2) > div:nth-of-type(2) span:nth-of-type(1)</value>
      <webElementGuid>3e73381c-057c-4348-bb04-1dcee1a95533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>9783c581-f16a-4dd6-84c3-a0f7cc0d3733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>24898caf-e624-4ac2-b316-ed9bdc3ac1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='lg:w-3/4 xl:w-4/5 flex-grow w-full']/div[3]//span[@class='vc-button__content']</value>
      <webElementGuid>3e0e5f26-2adb-413a-8677-7295ada23ee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[@class='lg:w-3/4 xl:w-4/5 flex-grow w-full']/div[4]//span[@class='vc-button__content']</value>
      <webElementGuid>99e0b039-7541-4420-846b-7f8776300889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
