<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PaymentMethodSelect</name>
   <tag></tag>
   <elementGuidId>6ea5456c-c5a3-4978-b812-f53ee3c0c13e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.flex-grow.vc-button--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f351db1-9445-4238-bc25-7265b598d98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>811f6486-9333-49c0-a9a3-949ebf00487b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>3a5dcf96-7989-4f25-8dc4-e937b5a4747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.flex-grow.vc-button--primary</value>
      <webElementGuid>7024809e-f959-424b-96ba-bceddc1914fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b4bc3717-680a-4d2f-8c6b-6e9dd4694ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
