<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PaymentMethod</name>
   <tag></tag>
   <elementGuidId>6d4085ec-6bcd-43cb-affb-1422523faf9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.w-full.flex-grow > div:nth-of-type(3) > div:nth-of-type(2) > div:nth-of-type(2) span:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[2]/div[2]/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f037bf8-7e17-4422-8e0d-e302dadad0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.w-full.flex-grow > div:nth-of-type(3) > div:nth-of-type(2) > div:nth-of-type(2) span:nth-of-type(1)</value>
      <webElementGuid>ae4d6cd6-0726-44a7-a11a-93af950ffcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>6dbdbacb-e68a-4d53-863e-5a599bc9cd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>76000dae-fbc3-475e-8641-edbc78530f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='lg:w-3/4 xl:w-4/5 flex-grow w-full']/div[3]//span[@class='vc-button__content']</value>
      <webElementGuid>11e9e373-c3e6-484a-af17-eee1f099aac1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div[2]/button/span</value>
      <webElementGuid>7e0bbe4c-ffba-431c-b0c9-af17bf16529e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
