<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_PaymentDetailsTitle</name>
   <tag></tag>
   <elementGuidId>8478054e-085a-46d2-8191-9214043c4231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
//h3[.='Payment details']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>22aca3d9-e2fd-4f30-8953-f9de0b62a79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-800 px-5 md:px-0 text-2xl lg:text-3xl font-bold uppercase mb-7</value>
      <webElementGuid>c861cbdf-29dd-42fb-9b08-9b7fa47469fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>
//h3[.='Payment details']</value>
      <webElementGuid>09d16a5e-43d5-404f-a448-32f1484a8de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment details</value>
      <webElementGuid>553d7bbc-013d-4846-b23b-0bab73432e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1fb868cb-5849-4317-b0ff-ba4371099098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
