<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ViewAllResults</name>
   <tag></tag>
   <elementGuidId>31e45aef-a772-4193-a159-c77575b786d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
.vc-button--sm > .vc-button__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1b6d405-ea6f-48e8-84ca-e266d052b0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.vc-button--sm > .vc-button__content</value>
      <webElementGuid>100a1fd4-4d27-4314-8d43-460421bc1c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>28d19312-346b-41e9-b62f-800d28f7dfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col font-lato overflow-x-hidden&quot;]/div[@class=&quot;z-10 shadow-md&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;flex items-center justify-between px-12 py-7 bg-gray-800 select-none absolute top-0 w-full z-20 transition-transform duration-300&quot;]/div[@class=&quot;flex flex-grow relative&quot;]/div[@class=&quot;absolute top-14 w-full flex flex-col gap-3 rounded bg-white shadow-lg overflow-hidden&quot;]/section[@class=&quot;px-5 py-4 border-t border-gray-100&quot;]/a[@class=&quot;rounded inline-flex justify-center items-center font-roboto-condensed cursor-pointer whitespace-nowrap bg-yellow-500 text-white hover:bg-yellow-600 h-8 text-sm uppercase px-4&quot;]</value>
      <webElementGuid>f30747b1-cac7-47ea-a0e0-d3f1d6266978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>285ff4c7-04ed-41a0-b102-0579ac26b163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>4b673a0e-dce1-4487-8dc6-f2287735dbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>96115e20-e163-4e72-9f7b-a71f29f8c33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>918608bf-e31a-4cc5-b4a0-556011df871e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0a6093a7-c944-431b-98e1-6168103679ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
