<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1div_ShippingAddressPopUp</name>
   <tag></tag>
   <elementGuidId>e9ec833a-1cbc-4e49-aedf-f40416e09739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
.my-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf0aecfa-aa0b-41e6-90db-ac353417418a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.my-8</value>
      <webElementGuid>3c0abe60-246e-417f-8d2a-4b34d6332b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>965b2241-eb29-4081-826c-ec6f08c1ea38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>60d9e14f-5c34-4666-aa8b-44f52b98c86a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
