<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1div_ShippingMethodPopUp</name>
   <tag></tag>
   <elementGuidId>bf5eacd9-f960-44cc-a398-2ff8cbbadb06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
.my-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>23eed541-4089-4d96-9305-358a610406ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.my-8</value>
      <webElementGuid>4e983cfc-ab16-4bd6-81cd-d0d30c72cdec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>f8d50f5b-5e42-498b-995f-c29941a98caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>04154be4-6c4e-45f0-9616-e8df0f41adaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
