<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ShippingAddressLine</name>
   <tag></tag>
   <elementGuidId>5cf67f25-8c4c-486f-a7cb-033474322567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
tbody > tr:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>293441f6-ac21-4da3-b73f-2421939bb634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
tbody > tr:nth-of-type(1)</value>
      <webElementGuid>ca4554a7-a1ef-42a6-8745-01156bfa467d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>97fd4b6a-0f29-46af-9760-21d2ef4f2f45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
