<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CleanCart</name>
   <tag></tag>
   <elementGuidId>a044584c-6f5e-4b22-999d-4b2cae82847e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.px-3.vc-button--secondary > .vc-button__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf37dd3d-4fcc-491f-8a0a-bd92d81d1bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>bead52a3-2186-4c1d-a6a2-181f8cceda01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col font-lato overflow-x-hidden&quot;]/div[@class=&quot;flex-grow flex flex-col&quot;]/div[@class=&quot;bg-gray-100 pt-7 pb-16 shadow-inner&quot;]/div[@class=&quot;max-w-screen-2xl md:px-12 mx-auto&quot;]/div[@class=&quot;flex flex-col lg:flex-row lg:flex-nowrap lg:space-x-6&quot;]/div[@class=&quot;lg:w-3/4 xl:w-4/5 flex-grow w-full&quot;]/div[@class=&quot;bg-white lg:mb-6 lg:rounded shadow lg:pb-11&quot;]/div[@class=&quot;xl:ml-28 lg:ml-6 xl:mr-11 lg:mr-6 lg:border lg:rounded&quot;]/div[@class=&quot;border-b&quot;]/div[@class=&quot;p-5 flex flex-wrap overflow-hidden space-x-4 lg:space-x-6&quot;]/div[@class=&quot;flex flex-col lg:flex-row lg:justify-between lg:items-center flex-1&quot;]/div[@class=&quot;flex items-start space-x-2 lg:space-x-4 xl:w-2/5 lg:justify-end&quot;]/div[@class=&quot;hidden lg:flex xl:w-1/4 flex-col space-y-1 text-xs font-semibold text-[color:var(--color-link)]&quot;]/span[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>bd40c956-f5f1-4d49-9079-307ccae75c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>fb3b03ec-9fd7-4f4d-9a0c-5c06e110c0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.px-3.vc-button--secondary > .vc-button__content</value>
      <webElementGuid>88b16fb5-4c3f-45b3-a092-6a27f58eb571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ce693b96-63c1-436b-ba22-534805fc8b1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
