<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CleanCartBlock</name>
   <tag></tag>
   <elementGuidId>ade0b02a-1903-4e37-ab2e-803f53af051b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='flex flex-col h-full py-12 justify-center items-center lg:items-start']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e650b2a-940b-4cbf-b450-f944b9e3a9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col h-full py-12 justify-center items-center lg:items-start</value>
      <webElementGuid>334fae59-81f8-4fd5-9f6f-337849bccfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='flex flex-col h-full py-12 justify-center items-center lg:items-start']</value>
      <webElementGuid>f04141a1-c67d-4515-b621-5af7279c3dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your cart is empty</value>
      <webElementGuid>634b8b60-c7ca-4deb-a733-68a122bba18c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6d7aaebe-1e62-4a67-b2af-a77e25ad6912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
