<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_EmptyCart</name>
   <tag></tag>
   <elementGuidId>fdcaac5d-2237-4f0b-9fd0-ca0b033f8083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class = 'text-black-800 text-2xl md:text-4xl font-bold mb-8' and (text() = 'Your cart is empty' or . = 'Your cart is empty')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b572b891-da09-4ad6-9836-c7d67a17f532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black-800 text-2xl md:text-4xl font-bold mb-8</value>
      <webElementGuid>749375e6-1e8b-425c-a3cd-3aa545a01069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col font-lato overflow-x-hidden&quot;]/div[@class=&quot;flex-grow flex flex-col&quot;]/div[@class=&quot;polygon-bg flex-grow&quot;]/div[@class=&quot;container mx-auto pt-5 pb-52 px-7 max-w-screen-lg&quot;]/div[@class=&quot;flex lg:space-x-24&quot;]/div[@class=&quot;w-full lg:w-1/2 lg:mt-8&quot;]/div[@class=&quot;flex flex-col h-full py-12 justify-center items-center lg:items-start&quot;]/h2[@class=&quot;text-black-800 text-2xl md:text-4xl font-bold mb-8&quot;]</value>
      <webElementGuid>2549d17d-5593-4c76-ae3f-295c9d36119e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your cart is empty</value>
      <webElementGuid>53796a5f-1162-4964-a4a6-a86bf675872f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c770891c-ac9f-45e5-9d35-a52017b323f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
