<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PrintButton</name>
   <tag></tag>
   <elementGuidId>1a0e16f9-4064-4923-8e77-91ed430a2d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'vc-button__content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7cf4f046-c612-41a0-9e43-5efb87be3823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>eacdf8b5-4bf2-4818-af66-6fe416e31746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print order</value>
      <webElementGuid>449d4d1e-0808-4141-8cd7-18a69a3485d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-8&quot;)/div[@class=&quot;fixed inset-0 z-50 overflow-y-auto&quot;]/div[@class=&quot;min-h-screen px-4 text-center&quot;]/div[@class=&quot;inline-block w-full my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-md max-w-2xl&quot;]/div[@class=&quot;px-6 py-4 flex items-center justify-between lg:justify-end space-x-4&quot;]/button[@class=&quot;vc-button vc-button--md vc-button--primary w-1/2 lg:w-auto uppercase flex-grow lg:flex-grow-0 inline-flex lg:px-10&quot;]/span[@class=&quot;vc-button__content&quot;]</value>
      <webElementGuid>bfab99cb-30c7-4837-a004-cf9b73ff78f9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
