<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxEmail</name>
   <tag></tag>
   <elementGuidId>2c1d7222-4d37-4571-a1c3-58728f75b17e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;8d05a60f-6e93-4a08-8208-4755a68e04f3&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[ng-model='organizationMemberChecks[member.id]']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
