<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ImageOfProducts</name>
   <tag></tag>
   <elementGuidId>c62996b3-f167-463a-aee5-ceac24d4c82a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='aerial-imaging-drones']/main/div/div/div/div/a/div/div/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;aerial-imaging-drones&quot;)/main[@class=&quot;wrapper main-content&quot;]/div[@class=&quot;grid grid-border&quot;]/div[@class=&quot;grid-item large--four-fifths grid-border--left&quot;]/div[@class=&quot;grid-uniform&quot;]/div[@class=&quot;grid-item large--one-quarter medium--one-third small--one-half comparable&quot;]/a[@class=&quot;product-grid-item Click&quot;]/div[@class=&quot;product-grid-image&quot;]/div[@class=&quot;product-grid-image--centered&quot;]/img[1][count(. | //*[@src = '//qademovc.blob.core.windows.net/catalog/3DRSOLO/1428965138000_1133723_168x168.jpg']) = count(//*[@src = '//qademovc.blob.core.windows.net/catalog/3DRSOLO/1428965138000_1133723_168x168.jpg'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//qademovc.blob.core.windows.net/catalog/3DRSOLO/1428965138000_1133723_168x168.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aerial-imaging-drones&quot;)/main[@class=&quot;wrapper main-content&quot;]/div[@class=&quot;grid grid-border&quot;]/div[@class=&quot;grid-item large--four-fifths grid-border--left&quot;]/div[@class=&quot;grid-uniform&quot;]/div[@class=&quot;grid-item large--one-quarter medium--one-third small--one-half comparable&quot;]/a[@class=&quot;product-grid-item Click&quot;]/div[@class=&quot;product-grid-image&quot;]/div[@class=&quot;product-grid-image--centered&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='aerial-imaging-drones']/main/div/div/div/div/a/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
