<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1div_PaymentMethodPopUp</name>
   <tag></tag>
   <elementGuidId>49542f0b-5126-4940-890f-7f088c34d60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
.my-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>418e26a2-167e-48de-b3e2-753991823088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.my-8</value>
      <webElementGuid>2d40d320-0f67-4ab0-82ab-c0a90bf808b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>98099ee3-0566-4221-9108-e73d6aad9511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7cd35480-d0ba-4ea4-b1ca-171c91cb8e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
