<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CompareCheckBox</name>
   <tag></tag>
   <elementGuidId>1fba7bb2-884a-436e-b1e1-1867e9f48334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
.gap-x-4 > div:nth-of-type(1) .ml-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='inkjet-printers']/main/div[3]/div[2]/div/div[2]/div[2]/div/div/add-to-compare-checkbox-migration/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fd82814-6d53-4429-a7a1-110c141010a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.gap-x-4 > div:nth-of-type(1) .ml-2</value>
      <webElementGuid>0a8fca79-c2b6-4cd9-90e1-8c1aaf6fff5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare</value>
      <webElementGuid>f2894517-3acf-4995-afbd-4b4a431dab89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='inkjet-printers']/main/div[3]/div[2]/div/div[2]/div[2]/div/div/add-to-compare-checkbox-migration/div</value>
      <webElementGuid>0f293bf0-a3ed-4168-973f-a0db6d8f61b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unavailable'])[1]/following::div[4]</value>
      <webElementGuid>29aa614e-9f6c-4a61-96d2-577613005c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/ each'])[1]/following::div[5]</value>
      <webElementGuid>ac63ccb7-b478-4ecd-b975-ad1e00fd413c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Epson Expression Premium XP-820 Wireless Color Photo Printer/Copier/Scanner/Fax Machine'])[1]/preceding::div[2]</value>
      <webElementGuid>fe1bed56-3b28-4e1c-ae5b-1aaf7cae8865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/add-to-compare-checkbox-migration/div</value>
      <webElementGuid>6169dd91-8c39-40cd-8c44-44e9309c9445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
