<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Register</name>
   <tag></tag>
   <elementGuidId>91c273f2-71ba-4e70-9259-4c067a639916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
.vc-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
.vc-button</value>
      <webElementGuid>df7228d1-c50a-4528-b790-0fbcd1a6d715</webElementGuid>
   </webElementProperties>
</WebElementEntity>
