<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RedistrationPopUpButton</name>
   <tag></tag>
   <elementGuidId>dd048952-63a1-4c5e-8478-61d8418cb371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
//span[.='Home page']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>
//span[.='Home page']</value>
      <webElementGuid>6e348e27-9952-4897-a7e9-8602725397a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>f1e5198f-d412-4d29-8fe3-c49a3badf1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.vc-button--md > .vc-button__content</value>
      <webElementGuid>a90e87f6-0299-4272-82d2-87945c7e6601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>span</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca985b15-d050-41b8-9791-e6b02f6ef8f6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
