<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RedistrationPopUp</name>
   <tag></tag>
   <elementGuidId>c772614c-c4af-49ec-8aa3-e7c6767669d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.my-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.my-8</value>
      <webElementGuid>0ffbba11-020a-4e6f-84d6-0789fd61117f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
