<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>741fe02c-570b-44bb-86f3-e025fa920bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[placeholder='Enter your e-mail address']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b40447df-0097-47bb-b395-b8969f935378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3322dc01-5f5e-4483-b797-33441dba4c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[placeholder='Enter your e-mail address']</value>
      <webElementGuid>22072faf-eb7f-4e38-a56b-f0a494c89df5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
