<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CompanyName</name>
   <tag></tag>
   <elementGuidId>97a11cbe-eb0d-4735-86cb-69c3ffac88a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
[placeholder='Enter organization name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9521b332-c7af-4649-92e7-402d28df98cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5d1557ce-aaf9-4e0b-b1dc-949baddf0885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
[placeholder='Enter organization name']</value>
      <webElementGuid>ec890e96-6689-4dc3-af30-b4977866a0cd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
