<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FirstName</name>
   <tag></tag>
   <elementGuidId>2f6c48ad-88db-4e47-bcd0-54e67e3515bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
[placeholder='Enter your first name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49bccf36-c8b7-4f88-82b7-01438c28ea25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>6b5a171f-25eb-455f-8752-212b64e4d44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>
[placeholder='Enter your first name']</value>
      <webElementGuid>ca9df2d2-5169-4245-a434-c5680da17edb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
