<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_RegisterPage</name>
   <tag></tag>
   <elementGuidId>b3ec279f-6230-4331-9de3-4717b8ba1503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>[href='/sign-up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2916a4b5-2aa4-4b81-9dd4-09b86dd30e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>
//a[.='Register now']</value>
      <webElementGuid>c5af9b31-8b9a-434a-a7da-4f1b1158cd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[href='/sign-up']</value>
      <webElementGuid>d87c5543-0b3f-4f5e-b3e6-c57f1e9acd0c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
