<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Road</name>
   <tag></tag>
   <elementGuidId>82a20e30-411c-4c21-a7c2-24bcaf0991fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;line1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>394bce63-60d5-4b00-98a6-6b939eee8923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required ng-touched</value>
      <webElementGuid>663b2041-011b-468e-b845-2829cc1bd02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>registration.address.line1</value>
      <webElementGuid>f97e4a95-67c1-4012-a571-6b461c606385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>line1</value>
      <webElementGuid>e1c0fc38-a478-4521-9247-ae1f267d9260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af8327dd-f2a4-42e2-8bdc-673144ea2a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street Address</value>
      <webElementGuid>a8a3c083-3f5f-47f9-a336-b00e0c3cb7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-customersregister ng-scope&quot;]/main[@class=&quot;container pt-4 pb-5 flex-grow-1&quot;]/div[@class=&quot;row justify-content-md-center ng-scope&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;steps ng-scope&quot;]/form[@class=&quot;ng-scope ng-dirty ng-valid-parse ng-valid-pattern ng-valid ng-valid-required&quot;]/section[@class=&quot;step ng-isolate-scope current&quot;]/div[@class=&quot;form-group ng-scope&quot;]/div[@class=&quot;form-group ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 mb-3 mb-sm-0&quot;]/input[@class=&quot;form-control ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required ng-touched&quot;]</value>
      <webElementGuid>f4c35aae-5087-4771-be9f-31ac2e6eb5b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='line1']</value>
      <webElementGuid>b2e472b2-96e6-4735-bb81-c197b27ed6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>bfa54a2f-17e9-43c8-9aa4-741e4150bbcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
