<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ProvinceAlberta</name>
   <tag></tag>
   <elementGuidId>fadc19c2-36a5-464b-b10a-e5fa2d27bf7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'Alberta' or . = 'Alberta')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='region']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;region&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>66a921ce-5f80-4e0f-a673-fe9bb3193e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.order-2 li:nth-of-type(1)</value>
      <webElementGuid>0f8412ad-f6dd-4a35-b25e-a177eaac31f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alberta</value>
      <webElementGuid>a64a794e-3eb7-43ae-814a-3ebb1b153992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[.='Alberta']</value>
      <webElementGuid>1a5db963-c309-49c9-b7d8-a28063ab611d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Alberta' or . = 'Alberta')]</value>
      <webElementGuid>e9629e23-886a-4627-829c-7dfcbef664f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/ul/li</value>
      <webElementGuid>cfdd2a35-5e72-44fc-bb65-7b2da1580ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
