<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddToCart</name>
   <tag></tag>
   <elementGuidId>defea500-e882-46bd-8b67-afd90f31df21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.p-6 > div:nth-of-type(2) > div:nth-of-type(2) > div:nth-of-type(2) button:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='1-stainless-steel-carriage-bolt-18-8-nl-19sm-finish-14-20-diathread-size-50-pk']/main/div[2]/div/ng-controller/div[2]/div[3]/div/div[2]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df7a1624-8136-4f22-9790-28b56df2d68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute z-10 flex items-center justify-center w-full h-full bg-white bg-opacity-70</value>
      <webElementGuid>bda6a864-6841-48fc-9b74-0e5cefce4452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col font-lato overflow-x-hidden&quot;]/div[@class=&quot;flex-grow flex flex-col&quot;]/div[@class=&quot;bg-gray-100 pt-7 pb-8 shadow-inner&quot;]/div[@class=&quot;max-w-screen-2xl px-5 md:px-12 mx-auto&quot;]/div[@class=&quot;flex flex-col lg:flex-row lg:space-x-8 mt-5&quot;]/div[@class=&quot;-mx-5 md:mx-0 lg:w-8/12 xl:w-9/12&quot;]/div[@class=&quot;flex flex-grow flex-col lg:flex-row p-6 lg:space-x-12 bg-white shadow-sm border rounded-none md:rounded&quot;]/div[@class=&quot;flex flex-col lg:w-2/3&quot;]/div[@class=&quot;flex flex-col mt-5&quot;]/div[@class=&quot;flex flex-row space-x-2.5 border border-gray-100 rounded-sm p-5 mb-5&quot;]/div[@class=&quot;flex-1 flex flex-col xl:flex-row xl:space-x-3&quot;]/div[@class=&quot;flex-1 xl:self-center flex flex-row items-center&quot;]/div[@class=&quot;flex flex-col w-full mt-4&quot;]/div[@class=&quot;flex relative&quot;]/div[@class=&quot;absolute z-10 flex items-center justify-center w-full h-full bg-white bg-opacity-70&quot;]</value>
      <webElementGuid>2a710a51-8c43-4571-81fc-24f84a830c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.p-6 > div:nth-of-type(2) > div:nth-of-type(2) > div:nth-of-type(2) button:nth-of-type(1)</value>
      <webElementGuid>9c154dd0-14f0-48af-9a31-35c8847c130e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='1-stainless-steel-carriage-bolt-18-8-nl-19sm-finish-14-20-diathread-size-50-pk']/main/div[2]/div/ng-controller/div[2]/div[3]/div/div[2]/div[2]/button</value>
      <webElementGuid>f2dd6171-4201-4bd1-a3a3-490e51efa111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::button[1]</value>
      <webElementGuid>a0802f9d-fbd6-4123-ac00-764c45704930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total price'])[1]/following::button[1]</value>
      <webElementGuid>f823ef70-1b01-4221-ba01-ac8ae58c75cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to list'])[1]/preceding::button[1]</value>
      <webElementGuid>33253beb-df0d-46f9-9cd1-429580069120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::button[1]</value>
      <webElementGuid>605515c3-b1c5-4425-b6ee-e81b0a7386aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to cart']/parent::*</value>
      <webElementGuid>5f6594b4-3d35-49e7-ae1c-9793243572d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>1bdbff4f-1d83-4a65-9315-e46a21a090a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
