<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_resetPasswordSuccess</name>
   <tag></tag>
   <elementGuidId>1fd56373-564b-4162-9d9b-c1d5b14316de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>
#resetSuccess</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
