<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconComparelistInProductsCard</name>
   <tag></tag>
   <elementGuidId>7547590d-e52d-4e5f-82f0-041c84bec870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;aerial-imaging-drones&quot;)/main[@class=&quot;wrapper main-content&quot;]/div[@class=&quot;grid grid-border&quot;]/div[@class=&quot;grid-item large--four-fifths grid-border--left&quot;]/div[@class=&quot;grid-uniform&quot;]/div[@class=&quot;grid-item large--one-quarter medium--one-third small--one-half comparable&quot;]/a[@class=&quot;product-grid-item Click&quot;]/div[@class=&quot;product-item--other&quot;]/add-to-compare-button[@class=&quot;ng-isolate-scope&quot;]/button[@id=&quot;addToCompareList&quot;][count(. | //*[@id = 'addToCompareList']) = count(//*[@id = 'addToCompareList'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addToCompareList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addToCompareList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[$ctrl.showButtonName ? '' : [$ctrl.customClass, 'btn-secondary'], $ctrl.containProduct ? 'disabled-compare-button':'']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aerial-imaging-drones&quot;)/main[@class=&quot;wrapper main-content&quot;]/div[@class=&quot;grid grid-border&quot;]/div[@class=&quot;grid-item large--four-fifths grid-border--left&quot;]/div[@class=&quot;grid-uniform&quot;]/div[@class=&quot;grid-item large--one-quarter medium--one-third small--one-half comparable&quot;]/a[@class=&quot;product-grid-item Click&quot;]/div[@class=&quot;product-item--other&quot;]/add-to-compare-button[@class=&quot;ng-isolate-scope&quot;]/button[@id=&quot;addToCompareList&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addToCompareList']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='aerial-imaging-drones']/main/div/div/div/div/a/div[2]/add-to-compare-button/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$995.99'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5,400.00'])[1]/preceding::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//add-to-compare-button/button</value>
   </webElementXpaths>
</WebElementEntity>
