<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconCartOnProductsCard</name>
   <tag></tag>
   <elementGuidId>e48a5d7b-4aa6-4225-b869-a4f36e773081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'icon icon-cart' and (not(contains(text(), 'Cart')) or not(contains(., 'Cart')))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='aerial-imaging-drones']/main/div/div/div/div/a/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-cart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aerial-imaging-drones&quot;)/main[@class=&quot;wrapper main-content&quot;]/div[@class=&quot;grid grid-border&quot;]/div[@class=&quot;grid-item large--four-fifths grid-border--left&quot;]/div[@class=&quot;grid-uniform&quot;]/div[@class=&quot;grid-item large--one-quarter medium--one-third small--one-half comparable&quot;]/a[@class=&quot;product-grid-item Click&quot;]/div[@class=&quot;product-item--other&quot;]/button[@class=&quot;btn btn-secondary AddShopCart ng-scope&quot;]/span[@class=&quot;icon icon-cart&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>not contain</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='aerial-imaging-drones']/main/div/div/div/div/a/div[2]/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
   </webElementXpaths>
</WebElementEntity>
