<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_OrderNotificationText</name>
   <tag></tag>
   <elementGuidId>a8500df5-5ebd-4223-bf68-a228b0f04d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Print order'])[1]/preceding::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.my-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>915b6614-615e-45c5-9a0a-88a04a3d54b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold text-condensed my-0 order-complete-title</value>
      <webElementGuid>4cef8c61-42d2-4d7d-9d57-c47b60d0a9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order CO211126-00001 has been successfully submitted. You will be notified via email when your order is ready for shipping</value>
      <webElementGuid>04e67470-507d-47dd-b532-934c6e129b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-cart ng-scope&quot;]/main[@class=&quot;container flex-grow-1 pt-4 pb-6 ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/vc-checkout-wizard[@class=&quot;ng-isolate-scope&quot;]/div[1]/vc-checkout-wizard-step[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;col-12 ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;card-header text-white bg-success&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-8 col-sm-9&quot;]/p[@class=&quot;font-weight-bold text-condensed my-0 order-complete-title&quot;]</value>
      <webElementGuid>e17a5caa-d9de-4213-b135-df5d5abc6a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print order'])[1]/preceding::p[1]</value>
      <webElementGuid>78606cdc-213b-40a6-8e49-f6847d7bc3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order']/parent::*</value>
      <webElementGuid>3ed6a07f-da45-4da6-a116-20f083ca796b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>dad46a6b-7822-4e15-943a-18914685e33e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
