<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SubmitPurchaseCode</name>
   <tag></tag>
   <elementGuidId>ecace827-e0d1-473b-9697-2a0924fdb95e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'purchaseOrderNumberSubmit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='purchaseOrderNumberSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#purchaseOrderNumberSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc648189-f47e-41cf-b62c-6a3800d60ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!purchaseOrderNumberExist() || purchaseOrderNumberChanged()</value>
      <webElementGuid>1b68311c-785d-4f05-9fc6-7a7a2145c2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchaseOrderNumberSubmit</value>
      <webElementGuid>b80f7695-7901-4309-b40f-e4413068c1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn d-flex align-items-center justify-content-center ng-scope btn-primary</value>
      <webElementGuid>14e8b169-a0c3-414e-99b6-fd69ea864fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>purchaseOrderNumberForm.$dirty ? 'btn-primary' : 'btn-outline-success'</value>
      <webElementGuid>67c67779-56e6-43c0-89d2-2a93a457fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!checkout.cart.purchaseOrderNumber &amp;&amp; !purchaseOrderNumberForm.$dirty</value>
      <webElementGuid>f3b2340a-1e4b-47c8-a8b3-8c019d87726a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>setPurchaseOrderNumber(purchaseOrderNumberForm)</value>
      <webElementGuid>9065b93b-4faa-4d76-8d28-d891c919255a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchaseOrderNumberSubmit&quot;)</value>
      <webElementGuid>b19a9f91-2020-43eb-99ba-afb8fdaff824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='purchaseOrderNumberSubmit']</value>
      <webElementGuid>2547e172-776f-4393-9fb9-e7c4da4dc894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Order'])[1]/following::button[1]</value>
      <webElementGuid>62d845c7-77d4-443b-8421-a18ffb98b64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$190.00'])[4]/following::button[1]</value>
      <webElementGuid>4677b8cd-b1d8-48c7-bb74-d10c038886cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotion code'])[1]/preceding::button[1]</value>
      <webElementGuid>daa166df-b138-4e9a-b34d-c0acca248a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company information'])[1]/preceding::button[2]</value>
      <webElementGuid>5b140e53-1bc2-445f-be01-024d7c636b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>87ef5e43-6eaa-4acd-99db-5cae8b9f8890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
