<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RemovePurchasedCode</name>
   <tag></tag>
   <elementGuidId>564790af-13de-44c5-8f5c-7b65a4c6c106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='removePurchaseOrderNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value> [ng-if='purchaseOrderNumberExist() &amp;&amp; !purchaseOrderNumberChanged()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be424209-2b0a-47e5-8c06-ca15c1780aff</webElementGuid>
   </webElementProperties>
</WebElementEntity>
