<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FieldPurchaseCode</name>
   <tag></tag>
   <elementGuidId>c47952b5-3643-4932-8cf0-9b9d3ad7ff28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='purchaseOrderNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#purchaseOrderNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5518f0f9-a807-45a3-9613-72c0c6b4661c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchaseOrderNumber</value>
      <webElementGuid>db884db9-3b1c-4dfc-b710-e46a662b64d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mr-2 ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>8a289534-8977-4252-9f28-3cb269468d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>checkout.cart.purchaseOrderNumber</value>
      <webElementGuid>c6e4b290-8b96-4473-b5d2-3191a9122afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purchaseOrderNumber</value>
      <webElementGuid>31b8b7f0-c27c-4fe8-b7c5-cc817985b2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter purchase order number</value>
      <webElementGuid>f51a7211-e5e7-4201-966a-fc0516a95d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebfb1a93-22a9-423e-8405-adaf93e2012e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchaseOrderNumber&quot;)</value>
      <webElementGuid>28b812e7-a140-4f01-a32b-1385c7465431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='purchaseOrderNumber']</value>
      <webElementGuid>df7a80e2-ceb7-40d5-aed9-db0a8f81316e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>33c779d7-4e7b-48ea-a881-775eeb0b18a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
