<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddNewShippingAddress</name>
   <tag></tag>
   <elementGuidId>8b2e2ffb-658c-45cd-8f6e-82a05493de6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'vc-button__content' and (text() = 'Add new address' or . = 'Add new address')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>19144950-7213-461a-9273-5ed00adf1490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-26&quot;)/div[@class=&quot;fixed inset-0 z-50 overflow-y-auto&quot;]/div[@class=&quot;min-h-screen px-4 text-center&quot;]/div[@class=&quot;inline-block w-full my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-md max-w-5xl&quot;]/div[@class=&quot;px-6 py-4 flex items-center justify-between lg:justify-end space-x-4&quot;]/button[@class=&quot;vc-button vc-button--md vc-button--primary vc-button--outline uppercase lg:mr-auto px-2&quot;]/span[@class=&quot;vc-button__content&quot;]</value>
      <webElementGuid>1610d1bb-fa49-4222-ba52-96160212f256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-button__content</value>
      <webElementGuid>ee4bdaf9-bac6-4003-a012-51b09f656743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add new address</value>
      <webElementGuid>7553630f-2a93-4ff1-8c27-5b9002626842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>3fc5c33e-eae6-4df3-9681-8db7bd8ad1ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
