<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>H1Total</name>
   <tag></tag>
   <elementGuidId>a3b1d6c7-284b-459e-9468-3ec670c155b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[@ng-bind = 'order.total.formattedAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>order.total.formattedAmount</value>
   </webElementProperties>
</WebElementEntity>
