<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StrongPrice</name>
   <tag></tag>
   <elementGuidId>d9bcfa25-5807-4c2d-a307-61d6156bb6f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@ng-bind = concat('prices[' , &quot;'&quot; , 'e1d43be2-8ab8-4378-bb95-43cc9269fd06' , &quot;'&quot; , '].actualPrice.formattedAmount')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>prices['e1d43be2-8ab8-4378-bb95-43cc9269fd06'].actualPrice.formattedAmount</value>
   </webElementProperties>
</WebElementEntity>
