<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_resetPasswordSuccess</name>
   <tag></tag>
   <elementGuidId>8ee02bdf-819d-4187-b155-e1db00e434de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>
#resetSuccess</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
