<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Featured</name>
   <tag></tag>
   <elementGuidId>2d30ac4d-14a5-43f3-8a74-78256973c03b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'sort']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sort']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sort</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6e6b88e-1869-4dd7-a83a-0939849ef623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sort</value>
      <webElementGuid>ffa2084f-873c-4793-9e7b-10adf509f2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-dark dropdown-toggle</value>
      <webElementGuid>ab40c7af-13eb-4f60-85d5-226577907636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a679e79-6619-479c-a188-d44bd015ee91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>42ba4a3e-7334-46cf-bb56-2f5e90e380f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
                Featured
            
            
        </value>
      <webElementGuid>536703bd-0352-44e2-b350-46645622e9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sort&quot;)</value>
      <webElementGuid>eb3c81f0-c930-4d15-a84b-828f93a8235b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sort']</value>
      <webElementGuid>423c8019-eead-4fbf-9a2f-e8ed22d55806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='carriage-bolts']/main/div[3]/div[2]/div/div/div/form/div[3]/div/a</value>
      <webElementGuid>6d8507c3-b026-42e0-924f-84a8dd4ed80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort results by:'])[1]/following::a[1]</value>
      <webElementGuid>7234802e-c695-44ad-885d-3cc553653626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page:'])[1]/following::a[4]</value>
      <webElementGuid>9b1fdb48-6a0d-4736-b5df-f8ce7dd95581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured'])[2]/preceding::a[1]</value>
      <webElementGuid>c3d0c1f5-3d6c-4ec8-96f7-59e0c090bcf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[44]</value>
      <webElementGuid>05f3558c-1011-464c-bafd-5ee9c759654c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>e2be6ea6-802b-40c3-8981-eb4e74115342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
