<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1div_PaymentMethodPopUp</name>
   <tag></tag>
   <elementGuidId>49542f0b-5126-4940-890f-7f088c34d60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.my-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4caabf19-77e7-4645-b9a5-e7aec0b0fb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.my-8</value>
      <webElementGuid>b9515415-12ba-404b-9983-be3ff88afa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>1c27a56b-e287-45f0-991e-8368a9100984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1ab4acd6-7b4f-472b-847e-97202c63b05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
