<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PopUpClearCart</name>
   <tag></tag>
   <elementGuidId>d59d4c78-8249-476c-b163-befb17f6f37f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>.my-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.my-8</value>
      <webElementGuid>4f710be2-1d6f-4c12-ba4e-29b915a0ba61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>aa365e1e-250c-4da7-ba62-939e26fd5c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
