<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_HideComparePupUp</name>
   <tag></tag>
   <elementGuidId>909c662d-09e7-47a4-97b0-8ed4afe766ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//span[.='Hide']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
