<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SubmitPromotionCode</name>
   <tag></tag>
   <elementGuidId>4dcbb33e-25cc-43c7-924a-7a9f91e4709e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'applyCouponSubmit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='applyCoupon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#applyCouponSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1e92d47-b94a-4d32-a69d-324d824ea237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!couponApplied</value>
      <webElementGuid>9c3e7a81-0809-4918-9f95-f9975c5ea6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applyCouponSubmit</value>
      <webElementGuid>32b01451-cb69-4ae5-adeb-b6326d854e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn d-flex align-items-center justify-content-center ng-scope btn-primary</value>
      <webElementGuid>353ffa3c-3d90-44e1-8dc7-693a7aa8ff36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>applyCouponForm.$dirty ? 'btn-primary' : 'btn-outline-success'</value>
      <webElementGuid>2420e749-3624-40b6-8258-f1b3d490d90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!checkout.coupon.code</value>
      <webElementGuid>25499142-204a-401d-9192-b29b50fd44aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>applyCoupon(checkout.coupon)</value>
      <webElementGuid>de1ad0d2-48bc-44a8-a713-eea3b2ff45a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applyCouponSubmit&quot;)</value>
      <webElementGuid>428ff0b2-c96e-45f9-a4d7-fee920b669da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='applyCouponSubmit']</value>
      <webElementGuid>818feeb6-092d-4f63-a880-72c9d307c4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotion code'])[1]/following::button[1]</value>
      <webElementGuid>f780bc0c-ad85-4789-b464-8f9f04ab9bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Order'])[1]/following::button[2]</value>
      <webElementGuid>ec1b1713-0cc7-4246-9343-2322ce83eae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company information'])[1]/preceding::button[1]</value>
      <webElementGuid>8ee23a71-0bb4-4a60-b4d1-5c134ae63eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer support'])[1]/preceding::button[1]</value>
      <webElementGuid>3bdb5ab6-f284-4cce-9e01-5124659d68b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/button</value>
      <webElementGuid>824e56b9-8db5-4d37-90d4-8bfd7c4a911e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
