<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FieldPromotionCode</name>
   <tag></tag>
   <elementGuidId>439a0171-73f7-45bb-80e0-bd5d671959ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='applyCoupon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#applyCoupon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ba0b5cf-7237-4a79-b377-99a934c6f7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applyCoupon</value>
      <webElementGuid>cff45453-3749-4509-97a6-a7702d3a05ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mr-2 ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>99e610f7-c8c4-4fb6-956e-5cf51c9e0663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>checkout.coupon.code</value>
      <webElementGuid>9a7014ce-a43d-4e61-9142-8e401b6bdda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applyCoupon</value>
      <webElementGuid>00854562-c9c5-4954-81d6-53c3daf09ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your code</value>
      <webElementGuid>c98c2273-141f-4e65-bdb3-7892407bc6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>couponApplied</value>
      <webElementGuid>3139d743-b608-45d8-9fc5-9ec2decbac58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8ecf3b7-773f-4f6d-91ee-d8f1860e7118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applyCoupon&quot;)</value>
      <webElementGuid>f4532b4d-5fe7-483a-b713-ec33543b22ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='applyCoupon']</value>
      <webElementGuid>9860e6dd-8253-434a-8550-660e08c3dc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/input</value>
      <webElementGuid>c5781b07-07da-4b09-90b4-739f31d5c37d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
