<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FilterMaterial5</name>
   <tag></tag>
   <elementGuidId>139ba0e7-02e6-4132-868f-e7d1efeb55e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'5 (3)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a3b2ea20-bab6-4974-9652-f72f8784fff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label d-inline-block text-body</value>
      <webElementGuid>c13f9639-7f7e-4e2d-bfb1-e52205cebb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vc-query-source</name>
      <type>Main</type>
      <value>{ terms: { 'MATERIAL GRADE': ['5'] } }</value>
      <webElementGuid>36415fc9-0049-42ab-9a81-1bc3d666825f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>switchable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a7da823-6f99-4230-b80e-c85c2450c24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://webstore-storefront.qa.govirto.com/B2B-store/carriage-bolts?terms=MATERIAL+GRADE:5#/</value>
      <webElementGuid>93d9b3ca-1cd2-4394-908f-f15c75104d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    5 (3)
                                </value>
      <webElementGuid>eda4e1b2-9b45-40d4-a8e5-9970adb89aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-31-3642-card&quot;)/div[@class=&quot;card-body&quot;]/ol[@class=&quot;list-unstyled mt-2 mb-0 ng-scope&quot;]/li[@class=&quot;custom-control custom-checkbox&quot;]/a[@class=&quot;custom-control-label d-inline-block text-body&quot;]</value>
      <webElementGuid>895a1fb7-aa7a-49b5-baa9-2e968a762967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-31-3642-card']/div/ol/li[2]/a</value>
      <webElementGuid>46f1af10-a080-483e-858a-e7abba48fde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[2]/following::a[1]</value>
      <webElementGuid>2f4e6197-afef-4bcf-b03f-89d482c0d0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MATERIAL GRADE'])[1]/following::a[2]</value>
      <webElementGuid>da1ccee6-2d4f-4315-b1f7-695d6cf833cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5']/parent::*</value>
      <webElementGuid>5c57218b-b735-4d30-8231-a3d42160bebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://webstore-storefront.qa.govirto.com/B2B-store/carriage-bolts?terms=MATERIAL+GRADE:5#/')]</value>
      <webElementGuid>31e746b2-9e98-4175-97e0-0e65e8e5a268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/ol/li[2]/a</value>
      <webElementGuid>97cb62fb-535c-4314-b6a7-6e2af2d1b0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
