<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1checkbox_AddGift</name>
   <tag></tag>
   <elementGuidId>0261abd3-7832-471a-8404-8dcc370c3ec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'border-gray-300 bg-white checked:bg-[color:var(--color-primary)] form-tick appearance-none flex-shrink-0 w-5 h-5 border-2 rounded-sm cursor-pointer disabled:cursor-not-allowed checked:border-transparent' and @type = 'checkbox']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-300 bg-white checked:bg-[color:var(--color-primary)] form-tick appearance-none flex-shrink-0 w-5 h-5 border-2 rounded-sm cursor-pointer disabled:cursor-not-allowed checked:border-transparent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col font-lato overflow-x-hidden&quot;]/div[@class=&quot;flex-grow flex flex-col&quot;]/div[@class=&quot;bg-gray-100 pt-7 pb-16 shadow-inner&quot;]/div[@class=&quot;max-w-screen-2xl md:px-12 mx-auto&quot;]/div[@class=&quot;flex flex-col lg:flex-row lg:flex-nowrap lg:space-x-6&quot;]/div[@class=&quot;lg:w-3/4 xl:w-4/5 flex-grow w-full&quot;]/div[@class=&quot;bg-white lg:mb-6 lg:rounded shadow-inner pb-8 lg:shadow&quot;]/div[@class=&quot;xl:ml-28 lg:ml-6 xl:mr-11 lg:mr-6 lg:border lg:rounded&quot;]/div[@class=&quot;border-b last:border-b-0 flex items-center justify-between px-7 py-6&quot;]/label[@class=&quot;flex items-center select-none cursor-pointer mr-7&quot;]/input[@class=&quot;border-gray-300 bg-white checked:bg-[color:var(--color-primary)] form-tick appearance-none flex-shrink-0 w-5 h-5 border-2 rounded-sm cursor-pointer disabled:cursor-not-allowed checked:border-transparent&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
</WebElementEntity>
