<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CountryCanada</name>
   <tag></tag>
   <elementGuidId>a6353642-d18a-4e7d-a6a7-dc2a3d0e4351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;countryCode&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'Canada' or . = 'Canada')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ea3a85ad-8433-4577-98a3-1dfe809eaabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css </name>
      <type>Main</type>
      <value>ul li:nth-child(40) </value>
      <webElementGuid>64b48535-7ebc-460a-bb06-5061f0d89c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canada</value>
      <webElementGuid>0ac1e77d-cadc-4944-bbe1-3553ecac7a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[.='Canada']</value>
      <webElementGuid>95a1660f-1c0f-4e75-9caa-28635a96637c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d9226b3-7721-45f9-8356-7a17c3ff982b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Canada' or . = 'Canada')]</value>
      <webElementGuid>9cb33878-f187-4fe7-9044-b7de4844b28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[40]</value>
      <webElementGuid>e3305b91-7e0a-4540-96f6-a59bec2d550d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
