<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectCountry</name>
   <tag></tag>
   <elementGuidId>dacdcd97-a27d-496f-a786-d46def9fdcc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='Country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.address.countryCode</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>x.code3 as x.name for x in $ctrl.countries</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Country</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select countryCanadaUnited StatesUnited KingdomAlbaniaAlgeriaAndorraAngolaArgentinaArmeniaArubaAntigua And BarbudaAustraliaAustriaAzerbaijanBangladeshBahamasBahrainBarbadosBelarusBelgiumBelizeBermudaBhutanBoliviaBosnia And HerzegovinaBotswanaBrazilBruneiBulgariaCambodiaRepublic of CameroonCayman IslandsChileChinaColombiaComorosCongoCosta RicaCôte d'IvoireCroatiaCuraçaoCyprusCzech RepublicDenmarkDominicaDominican RepublicEcuadorEgyptEl SalvadorEstoniaEthiopiaFaroe IslandsFijiFinlandFranceFrench PolynesiaGambiaGeorgiaGermanyGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuatemalaGuernseyGuyanaHaitiHondurasHong KongHungaryIcelandIndiaIndonesiaIrelandIsle Of ManIsraelItalyJamaicaJapanJerseyJordanKazakhstanKenyaKosovoKuwaitKyrgyzstanLatviaLebanonLiberiaLiechtensteinLithuaniaLuxembourgMacaoMacedonia, Republic OfMadagascarMalaysiaMaldivesMaltaMauritiusMexicoMoldova, Republic ofMonacoMongoliaMontenegroMoroccoMozambiqueMyanmarNamibiaNepalNetherlands AntillesNetherlandsNew ZealandNicaraguaNigerNigeriaNorwayOmanPakistanPalestinian Territory, OccupiedPanamaPapua New GuineaParaguayPeruPhilippinesPolandPortugalQatarReunionRomaniaRussiaRwandaSaint Kitts And NevisSaint LuciaSaint MartinSao Tome And PrincipeSamoaSaudi ArabiaSenegalSerbiaSeychellesSingaporeSint MaartenSlovakiaSloveniaSouth AfricaSouth KoreaSpainSri LankaSt. VincentSurinameSwedenSwitzerlandSyriaTaiwanThailandTanzania, United Republic OfTrinidad and TobagoTunisiaTurkeyTurkmenistanTurks and Caicos IslandsUgandaUkraineUnited Arab EmiratesUruguayUzbekistanVanuatuVenezuelaVietnamVirgin Islands, BritishYemenZambiaZimbabweAfghanistanAland IslandsAnguillaBeninBouvet IslandBritish Indian Ocean TerritoryBurkina FasoBurundiCape VerdeCentral African RepublicChadChristmas IslandCocos (Keeling) IslandsCongo, The Democratic Republic Of TheCook IslandsCubaDjiboutiEquatorial GuineaEritreaFalkland Islands (Malvinas)French GuianaFrench Southern TerritoriesGabonGuineaGuinea BissauHeard Island And Mcdonald IslandsHoly See (Vatican City State)Iran, Islamic Republic OfIraqKiribatiKorea, Democratic People's Republic OfLao People's Democratic RepublicLesothoLibyan Arab JamahiriyaMalawiMaliMartiniqueMauritaniaMayotteMontserratNauruNew CaledoniaNiueNorfolk IslandPitcairnSaint BarthélemySaint HelenaSaint Pierre And MiquelonSan MarinoSierra LeoneSolomon IslandsSomaliaSouth Georgia And The South Sandwich IslandsSudanSvalbard And Jan MayenSwazilandTajikistanTimor LesteTogoTokelauTongaTuvaluUnited States Minor Outlying IslandsWallis And FutunaWestern Sahara</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;multi-step windows chrome desktop page--no-banner page--logo-main page--show js flexbox flexboxlegacy rgba multiplebgs boxshadow opacity cssanimations csstransitions generatedcontent svg inlinesvg cors boxsizing display-table pointerevents placeholder mediaqueries floating-labels ng-scope&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;wrap vc-form&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;main__content&quot;]/vc-checkout-wizard[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;edit_checkout animate-floating-labels&quot;]/div[@class=&quot;step__sections&quot;]/vc-checkout-wizard-step[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;edit_checkout animate-floating-labels ng-scope&quot;]/div[@class=&quot;step__sections&quot;]/div[@class=&quot;section section--shipping-address&quot;]/div[@class=&quot;section__content&quot;]/div[@class=&quot;content-box&quot;]/vc-address[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;ng-pristine ng-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;form-fieldset&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;cols&quot;]/div[@class=&quot;col col-50&quot;]/div[@class=&quot;form-group form-select&quot;]/select[@class=&quot;form-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='Country']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip / Postal code'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone (optional)'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
