<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>1bb77490-74fe-4e51-9219-83d80998d2c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.rounded-0.border-top-0.border-left-0.border-right-0.border-bottom.border-gray-900.px-3.py-3.ng-binding</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-index ng-scope&quot;]/header[@class=&quot;d-none d-md-block&quot;]/nav[@class=&quot;navbar-dark bg-gray-900&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;flex-grow-1&quot;]/vc-search-bar-migration[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;input-group dropdown&quot;]/span[@class=&quot;input-group-append&quot;]/button[@class=&quot;btn btn-primary rounded-0 border-top-0 border-left-0 border-right-0 border-bottom border-gray-900 px-3 py-3 ng-binding&quot;][count(. | //*[(text() = 'Search' or . = 'Search')]) = count(//*[(text() = 'Search' or . = 'Search')])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary rounded-0 border-top-0 border-left-0 border-right-0 border-bottom border-gray-900 px-3 py-3 ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>$ctrl.submitLabel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;customer-logged-in template-index ng-scope&quot;]/header[@class=&quot;d-none d-md-block&quot;]/nav[@class=&quot;navbar-dark bg-gray-900&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;flex-grow-1&quot;]/vc-search-bar-migration[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;input-group dropdown&quot;]/span[@class=&quot;input-group-append&quot;]/button[@class=&quot;btn btn-primary rounded-0 border-top-0 border-left-0 border-right-0 border-bottom border-gray-900 px-3 py-3 ng-binding&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
   </webElementXpaths>
</WebElementEntity>
